name: FutureBans
version: 3.2.0
author: [JuniorWMG, Tobias Herzig]
main: net.coalcube.bansystem.spigot.BanSystemSpigot
commands:
  ban:
  unban:
  unmute:
  bansystem:
  bansys:
  kick:
  history:
    aliases: [hist]
  check:
  deletehistory:
  delhistory:
api-version: '1.13'